---
- name: install microk8s
  hosts: "192.168.122.74"
  become: yes
  tasks:
    - name: install microk8s
      snap:
        classic: yes
        name: microk8s
    - name: add userpermissions
      shell: "usermod -aG microk8s {{ lookup('env','USER') }}"
